### ISSUE TITLE
Weird issue with latest beta

### ISSUE THREAD

**Issue by r3mcos3** [custom-cards/button-card#254]
**Checklist**
- [* ] I updated the card to the latest version available
- [* ] I cleared the cache of my browser

**Describe the bug**
Since latest beta 0.103.0b0

i've have a error in log and it doesn't toggle my cover

`Log Details (ERROR)
Sat Dec 07 2019 08:44:29 GMT+0100 (Midden-Europese standaardtijd)
must contain at least one of entity_id, area_id.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 817, in validate_callable
    return schema(data)
  File "/usr/src/homeassistant/homeassistant/helpers/config_validation.py", line 94, in validate
    raise vol.Invalid("must contain at least one of {}.".format(", ".join(keys)))
voluptuous.error.Invalid: must contain at least one of entity_id, area_id.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 133, in handle_call_service
    connection.context(msg),
  File "/usr/src/homeassistant/homeassistant/core.py", line 1213, in async_call
    processed_data = handler.schema(service_data)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/validators.py", line 208, in __call__
    return self._exec((Schema(val) for val in self.validators), v)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/validators.py", line 287, in _exec
    raise e if self.msg is None else AllInvalid(self.msg, path=path)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/validators.py", line 283, in _exec
    v = func(v)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 276, in __call__
    raise er.MultipleInvalid([e])
voluptuous.error.MultipleInvalid: must contain at least one of entity_id, area_id.`

**Version of the card**
Version: 3.0.0

**To Reproduce**
This is the configuration I used:
`- type: custom:button-card
            icon: mdi:blinds
            entity: cover.rolgordijn
            name: Blinds
            tap_action:
              action: call-service
              service: cover.toggle
            hold_action:
              action: more-info  
            state:
              - value: "open"
                icon: mdi:blinds-open
              - value: "closed"
                icon: mdi:blinds`
```

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Expected behavior**
A clear and concise description of what you expected to happen.

**Desktop (please complete the following information):**
 - Browser Vivaldi 
 - Version 2.8.1664.44 (Stable channel) (64-bits)

**Smartphone (please complete the following information):**
 - Device: Oneplus 6
 - OS: Android 10.0.1
 - Browser Vivaldi Beta
 - Version 2.9.1741.33

**Additional context**
it was working on latest stable HA 0.102.3

**Comment by RomRider** [comment]
You're missing `service_data` with the `entity_id` in your `tap_action`

**Comment by r3mcos3** [comment]
Done what you sad, now it's working again.

but it worked on the latest stable, the way i had it
